{{ config(materialized='table') }}

WITH source AS (
    SELECT
        {{ dbt_utils.generate_surrogate_key(['Council:CouncilName']) }} AS council_id,
        {{ dbt_utils.generate_surrogate_key(['APPLICATIONTYPE']) }} AS application_type_id,
        {{ dbt_utils.generate_surrogate_key(['APPLICATIONSTATUS']) }} AS application_status_id,
        {{ dbt_utils.generate_surrogate_key(['DEVELOPMENTTYPE']) }} AS development_type_id,
        {{ dbt_utils.generate_surrogate_key(['SUBDIVISIONTYPE']) }} AS subdivision_type_id,
        {{ dbt_utils.generate_surrogate_key(['DETERMINATIONAUTHORITY']) }} AS determination_authority_id,
        Council:CouncilName::string AS CouncilName,
        LOCATION[0]:FullAddress::string AS FullAddress,
        LOCATION[0]:Postcode::string AS Postcode,
        LOCATION[0]:State::string AS State,
        LOCATION[0]:StreetName::string AS StreetName,
        LOCATION[0]:StreetNumber1::string AS StreetNumber1,
        LOCATION[0]:StreetType::string AS StreetType,
        LOCATION[0]:Suburb::string AS Suburb,
        LOCATION[0]:X::string AS X,
        LOCATION[0]:Y::string AS Y,
        APPLICATIONTYPE AS application_type,
        APPLICATIONSTATUS AS application_status,
        DEVELOPMENTTYPE[0] AS development_type,
        SUBDIVISIONTYPE[0] AS subdivision_type,
        DETERMINATIONAUTHORITY AS determination_authority,
        COSTOFDEVELOPMENT AS cost_of_development,
        NUMBEROFSTOREYS AS number_of_storeys,
        NUMBEROFEXISTINGLOTS AS number_of_existing_lots,
        NUMBEROFNEWDWELLINGS AS number_of_new_dwellings,
        NUMBEROFPROPOSEDLOTS AS number_of_proposed_lots,
        ACCOMPANIEDBYVPAFLAG AS accompanied_by_vpa,
        SUBDIVISIONPROPOSEDFLAG AS subdivision_proposed,
        EPIVARIATIONPROPOSEDFLAG AS epi_variation_proposed,
        DEVELOPMENTSUBJECTTOSICFLAG AS development_subject_to_sic
    FROM {{ source('developmentapplications', "onlinedav5") }}
)

SELECT
    council_id,
    application_type_id,
    application_status_id,
    development_type_id,
    subdivision_type_id,
    determination_authority_id,
    CouncilName,
    FullAddress,
    Postcode,
    State,
    StreetName,
    StreetNumber1,
    StreetType,
    Suburb,
    X,
    Y,
    application_type,
    application_status,
    development_type,
    subdivision_type,
    determination_authority,
    cost_of_development,
    number_of_storeys,
    number_of_existing_lots,
    number_of_new_dwellings,
    number_of_proposed_lots,
    accompanied_by_vpa,
    subdivision_proposed,
    epi_variation_proposed,
    development_subject_to_sic,
    CURRENT_TIMESTAMP() AS created_at
FROM source
